name: Cron Schedule
on:
  schedule: 
    - cron: '38 10 14 6 *'
  workflow_dispatch:

jobs:
  Schedule_Test:
    runs-on: ubuntu-latest
    steps:
      - name: Schedule
        run: echo 'Schedule worked'
